#ifndef COMPANION_CONFIG_H
#define COMPANION_CONFIG_H

#define COMPANION_I2C_SDA 21
#define COMPANION_I2C_SCL 22
#define COMPANION_DHT_PIN 4
#define COMPANION_MQ135_PIN 34
#define COMPANION_SD_CS 5
#define COMPANION_OLED_ADDR 0x3C
#define COMPANION_BUZZER_PIN 15
#define COMPANION_LED_PIN 2

#define COMPANION_TB6612_PWMA 25
#define COMPANION_TB6612_AIN1 26
#define COMPANION_TB6612_AIN2 27
#define COMPANION_TB6612_PWMB 14
#define COMPANION_TB6612_BIN1 12
#define COMPANION_TB6612_BIN2 13
#define COMPANION_TB6612_STBY 33
#define COMPANION_SERVO_PIN 32

#define COMPANION_HR_MIN 35.0f
#define COMPANION_HR_MAX 200.0f
#define COMPANION_SPO2_MIN 70.0f
#define COMPANION_SPO2_MAX 100.0f
#define COMPANION_OBJ_TEMP_MIN 20.0f
#define COMPANION_OBJ_TEMP_MAX 45.0f
#define COMPANION_EMA_ALPHA 0.25f
#define COMPANION_BASELINE_RATE 0.02f
#define COMPANION_BASELINE_SKIP 0.55f
#define COMPANION_BASELINE_MIN_SAMPLES 20
#define COMPANION_SIGNAL_Q_MIN 0.45f
#define COMPANION_RISK_RECHECK 0.35f
#define COMPANION_RISK_ELEVATED 0.65f
#define COMPANION_SD_WRITE_MS 30000
#define COMPANION_HEALTH_PERIOD_MS 500
#define COMPANION_DHT_PERIOD_MS 2000
#define COMPANION_DISPLAY_MS 1000
#define COMPANION_WIFI_STATUS_MS 15000
#define COMPANION_FLOOD_STALE_S 7200
#define COMPANION_FLOOD_WATCH 0.40f
#define COMPANION_FLOOD_HIGH 0.70f
#define COMPANION_FLOOD_HYST 0.08f
#define COMPANION_FLOOD_COOLDOWN_S 600

#ifndef COMPANION_DEMO_MODE
#define COMPANION_DEMO_MODE 0
#endif

#define COMPANION_MODEL_NAME "health_tree_v1"
#define COMPANION_MODEL_VERSION "1.0.0"

#endif
