#ifndef COMPANION_CONFIG_H
#define COMPANION_CONFIG_H

#include "pins.h"

#define COMPANION_HR_MIN 35.0f
#define COMPANION_HR_MAX 200.0f
#define COMPANION_SPO2_MIN 70.0f
#define COMPANION_SPO2_MAX 100.0f
#define COMPANION_OBJ_TEMP_MIN 5.0f
#define COMPANION_OBJ_TEMP_MAX 50.0f
#define COMPANION_EMA_ALPHA 0.25f
#define COMPANION_BASELINE_RATE 0.02f
#define COMPANION_BASELINE_SKIP 0.55f
#define COMPANION_BASELINE_MIN_SAMPLES 20
#define COMPANION_CAL_DURATION_MS 120000UL
#define COMPANION_CAL_MIN_SAMPLES 15
#define COMPANION_CAL_MIN_PPG 0.30f
#define COMPANION_CAL_INTERVAL_MS 1000UL
#define COMPANION_CAL_MLX_OPTIONAL 1
#define COMPANION_SIGNAL_Q_MIN 0.15f
#define COMPANION_MAX30102_LED_PA 0xFF
#define COMPANION_MAX30102_FINGER_IR_MIN 3000
#define COMPANION_MAX30102_BUF_MIN 4
#define COMPANION_MAX30102_BUF_SIZE 150
#define COMPANION_MAX30102_SAMPLE_HZ 100
#define COMPANION_MAX30102_HR_MIN_SAMPLES 40
#define COMPANION_MAX30102_SPO2_CONFIG 0x27
#define COMPANION_RISK_RECHECK 0.35f
#define COMPANION_RISK_ELEVATED 0.65f
#define COMPANION_SD_WRITE_MS 30000
#define COMPANION_HEALTH_PERIOD_MS 500
#define COMPANION_DHT_PERIOD_MS 2000
#define COMPANION_DISPLAY_MS 3000
#define COMPANION_WIFI_STATUS_MS 15000
#define COMPANION_FLOOD_STALE_S 7200
#define COMPANION_FLOOD_WATCH 0.40f
#define COMPANION_FLOOD_HIGH 0.70f
#define COMPANION_FLOOD_HYST 0.08f
#define COMPANION_FLOOD_COOLDOWN_S 600

#ifndef COMPANION_DEMO_MODE
#define COMPANION_DEMO_MODE 0
#endif

#define COMPANION_MODEL_NAME "health_tree_v1"
#define COMPANION_MODEL_VERSION "1.0.0"

#endif
