[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_upload.flash_size = 4MB
build_flags =
  -DCOMPANION_BOARD_ESP32
  -DCOMPANION_FLOOD_ONLY=1
  -DCORE_DEBUG_LEVEL=1
lib_deps =

[platformio]
src_dir = src
include_dir = include
