[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_upload.flash_size = 4MB
build_flags =
  -DCOMPANION_BOARD_ESP32
  -DCORE_DEBUG_LEVEL=1
build_src_filter =
  +<*>
  -<robot/>
  -<audio/>
lib_deps =
  Wire
  SPI
  SD
  WiFi
  HTTPClient
  sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
  adafruit/Adafruit MLX90614 Library @ ^2.1.5
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14

[platformio]
src_dir = src
include_dir = include
